### ISSUE TITLE
Server App not support CH343

### ISSUE THREAD

**Issue by SSV-Normandy** [SlimeVR/SlimeVR-Server#250]
I'm building a custom tracker board using CH343 to replace CH340 for smaller size, but the server app can't detect COM with CH343 properly. The COM port is good when download firmware through it.
![image](https://user-images.githubusercontent.com/23057907/193311698-fb773f20-0598-4e16-860a-149adc5ec552.png)
![image](https://user-images.githubusercontent.com/23057907/193311891-5ce9783b-0dec-403f-80da-7ddea90ad2a1.png)

**Comment by unlogisch04** [comment]
Should be fixed with
https://github.com/SlimeVR/SlimeVR-Server/pull/245
It will filter for "usb" and "seri"

**Comment by Louka3000** [comment]
@SSV-Normandy Can you confirm is this has been fixed (and close the issue if it is)?

Link to a build from latest commit (f3d32da4cd0b5221f0fb25176bf7fe10029faec4): https://github.com/SlimeVR/SlimeVR-Server/suites/8877865892/artifacts/405644841

**Comment by ButterscotchV** [comment]
Going to close this issue due to not getting a response, please re-open if #245 did not fix this and it continues to be an issue.
